# Generated by Django 3.0.8 on 2020-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=200)),
                ('publisher', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
