# Generated by Django 3.0.8 on 2020-07-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
